name: merge

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: read
  pull-requests: read

jobs:
  merge:
    if: ${{ github.event.label.name == 'merged' }}
    runs-on: ubuntu-latest
    name: merge
    steps:
      - name: Get Pull Request Number
        run: echo "PR_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')" >> "$GITHUB_ENV"
        shell: bash

      - name: Install governctl
        run: |
          set -xe
          echo "$PR_NUMBER"
          REF=$(echo ${{ github.event.number }} | sed 's/\//\\\//g')
          echo "$REF"
          echo ${{ github.event.number }}
          gh pr view --json number -q .number
